// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/product/product.proto

package laracom_service_product

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Product struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	BrandId              uint32   `protobuf:"varint,2,opt,name=brand_id,json=brandId,proto3" json:"brand_id,omitempty"`
	Sku                  string   `protobuf:"bytes,3,opt,name=sku,proto3" json:"sku,omitempty"`
	Name                 string   `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Slug                 string   `protobuf:"bytes,5,opt,name=slug,proto3" json:"slug,omitempty"`
	Description          string   `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	Cover                string   `protobuf:"bytes,7,opt,name=cover,proto3" json:"cover,omitempty"`
	Quantity             uint32   `protobuf:"varint,8,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Price                float32  `protobuf:"fixed32,9,opt,name=price,proto3" json:"price,omitempty"`
	SalePrice            float32  `protobuf:"fixed32,10,opt,name=sale_price,json=salePrice,proto3" json:"sale_price,omitempty"`
	Status               uint32   `protobuf:"varint,11,opt,name=status,proto3" json:"status,omitempty"`
	Length               float32  `protobuf:"fixed32,12,opt,name=length,proto3" json:"length,omitempty"`
	Width                float32  `protobuf:"fixed32,13,opt,name=width,proto3" json:"width,omitempty"`
	Height               float32  `protobuf:"fixed32,14,opt,name=height,proto3" json:"height,omitempty"`
	Weight               float32  `protobuf:"fixed32,15,opt,name=weight,proto3" json:"weight,omitempty"`
	DistanceUnit         string   `protobuf:"bytes,16,opt,name=distance_unit,json=distanceUnit,proto3" json:"distance_unit,omitempty"`
	MassUnit             string   `protobuf:"bytes,17,opt,name=mass_unit,json=massUnit,proto3" json:"mass_unit,omitempty"`
	CreatedAt            string   `protobuf:"bytes,18,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,19,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Product) Reset()         { *m = Product{} }
func (m *Product) String() string { return proto.CompactTextString(m) }
func (*Product) ProtoMessage()    {}
func (*Product) Descriptor() ([]byte, []int) {
	return fileDescriptor_14fbc13de7c38f78, []int{0}
}

func (m *Product) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Product.Unmarshal(m, b)
}
func (m *Product) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Product.Marshal(b, m, deterministic)
}
func (m *Product) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Product.Merge(m, src)
}
func (m *Product) XXX_Size() int {
	return xxx_messageInfo_Product.Size(m)
}
func (m *Product) XXX_DiscardUnknown() {
	xxx_messageInfo_Product.DiscardUnknown(m)
}

var xxx_messageInfo_Product proto.InternalMessageInfo

func (m *Product) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Product) GetBrandId() uint32 {
	if m != nil {
		return m.BrandId
	}
	return 0
}

func (m *Product) GetSku() string {
	if m != nil {
		return m.Sku
	}
	return ""
}

func (m *Product) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Product) GetSlug() string {
	if m != nil {
		return m.Slug
	}
	return ""
}

func (m *Product) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Product) GetCover() string {
	if m != nil {
		return m.Cover
	}
	return ""
}

func (m *Product) GetQuantity() uint32 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

func (m *Product) GetPrice() float32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Product) GetSalePrice() float32 {
	if m != nil {
		return m.SalePrice
	}
	return 0
}

func (m *Product) GetStatus() uint32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *Product) GetLength() float32 {
	if m != nil {
		return m.Length
	}
	return 0
}

func (m *Product) GetWidth() float32 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *Product) GetHeight() float32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *Product) GetWeight() float32 {
	if m != nil {
		return m.Weight
	}
	return 0
}

func (m *Product) GetDistanceUnit() string {
	if m != nil {
		return m.DistanceUnit
	}
	return ""
}

func (m *Product) GetMassUnit() string {
	if m != nil {
		return m.MassUnit
	}
	return ""
}

func (m *Product) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *Product) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

type Request struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_14fbc13de7c38f78, []int{1}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

type Response struct {
	Product              *Product   `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	Products             []*Product `protobuf:"bytes,2,rep,name=products,proto3" json:"products,omitempty"`
	Errors               []*Error   `protobuf:"bytes,3,rep,name=errors,proto3" json:"errors,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_14fbc13de7c38f78, []int{2}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetProduct() *Product {
	if m != nil {
		return m.Product
	}
	return nil
}

func (m *Response) GetProducts() []*Product {
	if m != nil {
		return m.Products
	}
	return nil
}

func (m *Response) GetErrors() []*Error {
	if m != nil {
		return m.Errors
	}
	return nil
}

type Error struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_14fbc13de7c38f78, []int{3}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func init() {
	proto.RegisterType((*Product)(nil), "laracom.service.product.Product")
	proto.RegisterType((*Request)(nil), "laracom.service.product.Request")
	proto.RegisterType((*Response)(nil), "laracom.service.product.Response")
	proto.RegisterType((*Error)(nil), "laracom.service.product.Error")
}

func init() { proto.RegisterFile("proto/product/product.proto", fileDescriptor_14fbc13de7c38f78) }

var fileDescriptor_14fbc13de7c38f78 = []byte{
	// 508 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x94, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x86, 0x89, 0xdd, 0x24, 0xf6, 0xa4, 0x09, 0x65, 0x41, 0xb0, 0xb4, 0x2a, 0x32, 0xe1, 0x92,
	0x53, 0x90, 0x8a, 0xc4, 0x01, 0xc1, 0x21, 0x02, 0x54, 0x21, 0x21, 0x51, 0x19, 0xf5, 0x1c, 0x6d,
	0xbd, 0xa3, 0x64, 0x85, 0x63, 0xbb, 0xbb, 0xeb, 0x56, 0xbc, 0x0e, 0xcf, 0xc1, 0x2b, 0xf1, 0x0e,
	0x68, 0x67, 0xd7, 0x15, 0x02, 0x85, 0xf6, 0x90, 0x93, 0xe7, 0xff, 0xfe, 0x99, 0xd9, 0xf1, 0x7a,
	0x64, 0x38, 0x6a, 0x74, 0x6d, 0xeb, 0x97, 0x8d, 0xae, 0x65, 0x5b, 0xd8, 0xee, 0x39, 0x27, 0xca,
	0x9e, 0x94, 0x42, 0x8b, 0xa2, 0xde, 0xcc, 0x0d, 0xea, 0x2b, 0x55, 0xe0, 0x3c, 0xd8, 0xd3, 0x5f,
	0x31, 0x0c, 0xcf, 0x7c, 0xcc, 0x26, 0x10, 0x29, 0xc9, 0x7b, 0x59, 0x6f, 0x36, 0xce, 0x23, 0x25,
	0xd9, 0x53, 0x48, 0x2e, 0xb4, 0xa8, 0xe4, 0x52, 0x49, 0x1e, 0x11, 0x1d, 0x92, 0xfe, 0x24, 0xd9,
	0x01, 0xc4, 0xe6, 0x5b, 0xcb, 0xe3, 0xac, 0x37, 0x4b, 0x73, 0x17, 0x32, 0x06, 0x7b, 0x95, 0xd8,
	0x20, 0xdf, 0x23, 0x44, 0xb1, 0x63, 0xa6, 0x6c, 0x57, 0xbc, 0xef, 0x99, 0x8b, 0x59, 0x06, 0x23,
	0x89, 0xa6, 0xd0, 0xaa, 0xb1, 0xaa, 0xae, 0xf8, 0x80, 0xac, 0x3f, 0x11, 0x7b, 0x04, 0xfd, 0xa2,
	0xbe, 0x42, 0xcd, 0x87, 0xe4, 0x79, 0xc1, 0x0e, 0x21, 0xb9, 0x6c, 0x45, 0x65, 0x95, 0xfd, 0xce,
	0x13, 0x1a, 0xe6, 0x46, 0xbb, 0x8a, 0x46, 0xab, 0x02, 0x79, 0x9a, 0xf5, 0x66, 0x51, 0xee, 0x05,
	0x3b, 0x06, 0x30, 0xa2, 0xc4, 0xa5, 0xb7, 0x80, 0xac, 0xd4, 0x91, 0x33, 0xb2, 0x1f, 0xc3, 0xc0,
	0x58, 0x61, 0x5b, 0xc3, 0x47, 0xd4, 0x2e, 0x28, 0xc7, 0x4b, 0xac, 0x56, 0x76, 0xcd, 0xf7, 0xa9,
	0x24, 0x28, 0x77, 0xc8, 0xb5, 0x92, 0x76, 0xcd, 0xc7, 0xfe, 0x10, 0x12, 0x2e, 0x7b, 0x8d, 0x6a,
	0xb5, 0xb6, 0x7c, 0xe2, 0xb3, 0xbd, 0x72, 0xfc, 0xda, 0xf3, 0xfb, 0x9e, 0x7b, 0xc5, 0x5e, 0xc0,
	0x58, 0x2a, 0x63, 0x45, 0x55, 0xe0, 0xb2, 0xad, 0x94, 0xe5, 0x07, 0xf4, 0x92, 0xfb, 0x1d, 0x3c,
	0xaf, 0x94, 0x65, 0x47, 0x90, 0x6e, 0x84, 0x31, 0x3e, 0xe1, 0x01, 0x25, 0x24, 0x0e, 0x90, 0x79,
	0x0c, 0x50, 0x68, 0x14, 0x16, 0xe5, 0x52, 0x58, 0xce, 0xc8, 0x4d, 0x03, 0x59, 0x90, 0xdd, 0x36,
	0xb2, 0xb3, 0x1f, 0x7a, 0x3b, 0x90, 0x85, 0x9d, 0xa6, 0x30, 0xcc, 0xf1, 0xb2, 0x45, 0x63, 0xa7,
	0x3f, 0x7b, 0x90, 0xe4, 0x68, 0x9a, 0xba, 0x32, 0xc8, 0xde, 0xc0, 0x30, 0xac, 0x04, 0x2d, 0xc0,
	0xe8, 0x24, 0x9b, 0x6f, 0x59, 0x99, 0x79, 0x58, 0x97, 0xbc, 0x2b, 0x60, 0x6f, 0x21, 0x09, 0xa1,
	0xe1, 0x51, 0x16, 0xdf, 0xa9, 0xf8, 0xa6, 0x82, 0xbd, 0x86, 0x01, 0x6a, 0x5d, 0x6b, 0xc3, 0x63,
	0xaa, 0x7d, 0xb6, 0xb5, 0xf6, 0xa3, 0x4b, 0xcb, 0x43, 0xf6, 0xf4, 0x1d, 0xf4, 0x09, 0xb8, 0x2d,
	0x2b, 0x6a, 0x89, 0x34, 0x77, 0x3f, 0xa7, 0xf8, 0xef, 0x2d, 0x8b, 0xfe, 0xd9, 0xb2, 0x93, 0x1f,
	0x31, 0x4c, 0xc2, 0x30, 0x5f, 0xfd, 0x39, 0xec, 0x0b, 0x0c, 0xde, 0xd3, 0x3d, 0xb2, 0x5b, 0xe7,
	0x3f, 0x7c, 0xbe, 0x35, 0xa3, 0xbb, 0xd2, 0xe9, 0x3d, 0xd7, 0xf0, 0x03, 0x96, 0xb8, 0xd3, 0x86,
	0xe7, 0xf4, 0x29, 0x77, 0xd5, 0xf0, 0x33, 0xc4, 0xa7, 0x68, 0x77, 0x38, 0xde, 0x29, 0xda, 0x45,
	0x59, 0xfe, 0xa7, 0x61, 0xd8, 0xbe, 0x3b, 0x35, 0xbc, 0x18, 0xd0, 0xdf, 0xeb, 0xd5, 0xef, 0x00,
	0x00, 0x00, 0xff, 0xff, 0xd1, 0xb4, 0xbf, 0xf1, 0xdc, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for ProductService service

type ProductServiceClient interface {
	Create(ctx context.Context, in *Product, opts ...client.CallOption) (*Response, error)
	Delete(ctx context.Context, in *Product, opts ...client.CallOption) (*Response, error)
	Update(ctx context.Context, in *Product, opts ...client.CallOption) (*Response, error)
	Get(ctx context.Context, in *Product, opts ...client.CallOption) (*Response, error)
	GetAll(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
}

type productServiceClient struct {
	c           client.Client
	serviceName string
}

func NewProductServiceClient(serviceName string, c client.Client) ProductServiceClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "laracom.service.product"
	}
	return &productServiceClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *productServiceClient) Create(ctx context.Context, in *Product, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "ProductService.Create", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) Delete(ctx context.Context, in *Product, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "ProductService.Delete", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) Update(ctx context.Context, in *Product, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "ProductService.Update", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) Get(ctx context.Context, in *Product, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "ProductService.Get", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) GetAll(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "ProductService.GetAll", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ProductService service

type ProductServiceHandler interface {
	Create(context.Context, *Product, *Response) error
	Delete(context.Context, *Product, *Response) error
	Update(context.Context, *Product, *Response) error
	Get(context.Context, *Product, *Response) error
	GetAll(context.Context, *Request, *Response) error
}

func RegisterProductServiceHandler(s server.Server, hdlr ProductServiceHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&ProductService{hdlr}, opts...))
}

type ProductService struct {
	ProductServiceHandler
}

func (h *ProductService) Create(ctx context.Context, in *Product, out *Response) error {
	return h.ProductServiceHandler.Create(ctx, in, out)
}

func (h *ProductService) Delete(ctx context.Context, in *Product, out *Response) error {
	return h.ProductServiceHandler.Delete(ctx, in, out)
}

func (h *ProductService) Update(ctx context.Context, in *Product, out *Response) error {
	return h.ProductServiceHandler.Update(ctx, in, out)
}

func (h *ProductService) Get(ctx context.Context, in *Product, out *Response) error {
	return h.ProductServiceHandler.Get(ctx, in, out)
}

func (h *ProductService) GetAll(ctx context.Context, in *Request, out *Response) error {
	return h.ProductServiceHandler.GetAll(ctx, in, out)
}
